// Contenu Partie 2 — Fonctionnement détaillé des modules
module.exports = [
  {
    title: "4. Fonctionnement détaillé des modules",
    blocks: [
      { type: "p", text: "Ce chapitre décrit le comportement réel de chaque module, dans l'ordre du parcours type d'un jeune : lecture du tableau de bord, réalisation de missions, constitution de l'éligibilité au prêt, gestion du portefeuille, croissance par le parrainage et l'investissement, divertissement, assistance, et enfin pilotage côté administrateur. Les règles et montants cités sont ceux du code et de la configuration administrative actuelle." },

      { type: "h2", text: "4.1 Tableau de bord du jeune (Étape 1)" },
      { type: "p", text: "Le tableau de bord est la première page visible après la connexion. Il a été reconstruit conformément à la spécification « Étape 1 » : salutation personnalisée (« Bonjour, prénom »), quatre cartes statistiques (solde disponible, gains du jour, compteur d'images 7/10 avec barre de progression, parrainages 3/5), grande carte d'objectif vers 2 500 FCFA avec pourcentage et reste à gagner, carte d'éligibilité au prêt de 5 000 FCFA listant chaque condition remplie ou non, carte « Ma caution » au cadenas distincte du solde, missions disponibles avec bouton « Voir la mission » (jamais « Générer », la création d'image se faisant à l'extérieur du site), bloc pédagogique « Comment gagner ? » en cinq étapes, et activité récente avec historique." },
      { type: "p", text: "À ce stade, ces données sont volontairement fictives afin de valider le design ; elles sont structurées exactement comme les réponses des API existantes (missions/dashboard, missions/campaigns, referral/list), de sorte que le remplacement par les vraies données de la base se fera sans refonte de l'interface. La navigation interne du tableau de bord offre sept entrées : Tableau, Missions, Mes images, Portefeuille (raccourci vers l'écran portefeuille), Éligibilité, Mes prêts et Parrainage. L'en-tête permanent affiche le logo « Jeune Élan », la cloche de notifications (compteur de non-lues rafraîchi toutes les quinze secondes) et l'accès au profil." },

      { type: "h2", text: "4.2 Missions rémunérées et validation par intelligence artificielle" },
      { type: "p", text: "Une mission correspond à une campagne créée par l'administrateur : marque, nom, brief créatif, format attendu, style, contraintes, récompense (25 FCFA par image validée), limite quotidienne par jeune (10 images par jour) et volume maximal global. Le jeune consulte le brief, crée son image avec l'outil d'intelligence artificielle de son choix en dehors de la plateforme, puis l'importe : l'image est envoyée en base 64, enregistrée avec une empreinte de similarité, et le jeune peut suivre son compteur journalier. Le compteur se réinitialise chaque jour." },
      { type: "p", text: "La validation est asynchrone et automatique. Le système transmet l'image à un modèle de vision par API, qui évalue la conformité au brief, l'originalité, l'absence de doublon et le caractère non téléchargé d'internet. Cinq statuts en résultent : en attente, validée (+25 FCFA crédités sur le solde missions), refusée, doublon (image trop similaire à une soumission précédente) et non conforme. Chaque décision est notifiée au jeune avec le motif ; les images non retenues ne rapportent rien. Les images sont purgées quotidiennement pour libérer l'espace de stockage, tandis que les gains restent acquis dans l'historique des transactions. Ce module est le cœur du modèle : c'est lui qui transforme le temps du jeune en monnaie interne, et c'est donc lui qui détermine la charge financière décrite au chapitre 6." },

      { type: "h2", text: "4.3 Objectif 2 500 FCFA, caution et micro-prêts" },
      { type: "p", text: "Le parcours de crédit est balisé par trois conditions cumulatives. Premièrement, le jeune doit cumuler au moins 2 500 FCFA de gains issus exclusivement des missions validées — la progression vers cet objectif ignore volontairement les dépôts personnels, la caution et l'argent d'un prêt, conformément à la règle du programme. Deuxièmement, il doit bloquer une caution de 5 000 FCFA, montant sécurisé, affiché au cadenas et explicitement exclu du solde disponible au retrait. Troisièmement, il doit compter 5 parrainages validés (seuil du petit prêt). Le tableau d'éligibilité affiche en permanence ces conditions avec leur état, le niveau de confiance de l'utilisateur (Débutant, Actif, Éligible, Fiable) et un bouton d'action qui devient « Demander un prêt » une fois tout rempli." },
      { type: "p", text: "Deux formats de prêt existent : 5 000 FCFA (conditions ci-dessus) et 10 000 FCFA (conditions renforcées). La demande enregistrée passe par une file d'attente ; elle est approuvée manuellement par l'administrateur, devient active avec une échéance à 30 jours, puis passe en remboursement partiel ou total. Aucun intérêt n'est prélevé par le code : le prêt est remboursé à montant nominal. Les statuts gérés couvrent l'ensemble du cycle : en attente, approuvé, actif, en remboursement, en retard, remboursé et refusé, avec notifications à chaque transition et blocage de toute nouvelle demande tant qu'un prêt est actif ou en retard. L'éligibilité ne garantit donc pas l'octroi : la décision finale reste administrative." },

      { type: "h2", text: "4.4 Portefeuille, dépôts et retraits" },
      { type: "p", text: "Le portefeuille agrège l'ensemble des avoirs du jeune sur des comptes séparés : compte principal, compte missions, compte jeu, compte investissement et compte projet, avec solde total, gains cumulés, pertes cumulées et historique complet des transactions. Les mouvements internes (récompenses, gains de jeu, rendements, bonus, prêts) alimentent les comptes correspondants sans jamais se mélanger avec les dépôts d'origine externe, ce qui facilite la traçabilité." },
      { type: "p", text: "Les dépôts externes transitent par trois canaux : le portefeuille YAS, le réseau TRX (Tron) avec adresse de dépôt et vérification on-chain via un explorateur, et le mobile money. Tout dépôt est d'abord enregistré en attente, puis crédité après validation manuelle par l'administrateur ; un seul dépôt en attente est autorisé simultanément. Le premier dépôt validé déclenche une condition de sécurité : le jeune doit attendre 24 heures avant de pouvoir demander un retrait. Les retraits sont soumis à validation administrative et à un dispositif anti-abus particulier : le nombre de parrainages requis augmente avec le nombre de retraits déjà effectués, ce qui rend chaque retrait successif plus exigeant. Les fonds sortent vers le canal choisi, avec une conversion TRX vers mobile money le cas échéant. Ce verrou progressif est présenté au chapitre 6 pour ce qu'il est : un frein à la sortie de trésorerie qui retarde les engagements mais ne les crée pas." },

      { type: "h2", text: "4.5 Parrainage et niveaux d'investissement" },
      { type: "p", text: "Chaque utilisateur reçoit un code de parrainage unique, consultable et copiable depuis l'écran dédié. Un filleul est comptabilisé lorsqu'il s'inscrit avec ce code ; il devient « validé » lorsqu'il devient actif (dépôt effectué). Le parrain touche un bonus de 20 % par filleul validé et les parrainages servent de clé de déblocage dans tout le système : 5 pour le petit prêt, 12 pour le niveau 2 d'investissement, 25 pour le niveau 3, et un nombre croissant pour déverrouiller les retraits successifs. Le parrainage est donc le moteur de croissance virale de la plateforme — et en même temps, comme chaque filleul actif génère du passif de missions, l'agent d'accroissement du passif." },
      { type: "p", text: "Le module d'investissement propose trois niveaux libellés en dollars : niveau 1 « Débutant » de 5 à 15 $ (sans parrainage requis), niveau 2 « Business » de 65 à 250 $ (12 parrainages), niveau 3 « Elite » de 500 à 3 000 $ (25 parrainages). Chaque placement rapporte 5 % de son montant, collectables quotidiennement (« collecte quotidienne illimitée » selon l'interface). Cette mécanique, vérifiée dans la route de réclamation, est le paramètre financier le plus explosif du système : un placement de 3 000 $ émet théoriquement 150 $ par jour. Les conséquences sont analysées au chapitre 6." },

      { type: "h2", text: "4.6 Jeu, trading et arène" },
      { type: "p", text: "La roue de la fortune dispose de douze segments : gains de 0,10 à 10,00 $ et cases perdantes. Chaque tour a un coût, prélevé sur le compte jeu ; le jeune dispose de dix tours par jour et le résultat du tirage est déterminé côté serveur, ce qui interdit la triche côté client. Les gains alimentent le compte jeu, consultable et retirable selon les mêmes règles que les autres comptes." },
      { type: "p", text: "Le trading est une simulation de marché : cours, graphiques, ouverture et fermeture de positions sur le solde de trading dédié, avec historique des gains et pertes. L'arène ajoute une dimension compétitive en classant les meilleurs traders de la plateforme. Ces modules n'émettent pas de monnaie externe : ils font circuler les soldes internes et augmentent l'engagement quotidien, mais leurs gains s'ajoutent au passif global dès qu'ils deviennent retirables." },

      { type: "h2", text: "4.7 Chat, support et notifications" },
      { type: "p", text: "Le centre d'assistance combine un assistant conversationnel automatisé (réponses immédiates sur le fonctionnement, les missions, les prêts et les dépôts) et une escalade vers un humain : le jeune peut ouvrir un ticket, échanger en temps réel avec l'administrateur via Socket.io, et clôturer la conversation. L'administrateur répond depuis son panneau et peut gérer les conversations ouvertes. Le système de notifications couvre la vie du compte : validation ou refus d'image, seuils atteints, statut de prêt, statut de dépôt et de retrait, messages de diffusion collective envoyés par l'administration. La cloche affiche le compteur de non-lues avec un rafraîchissement toutes les quinze secondes, et une notification du jour s'affiche sur l'écran d'accueil." },

      { type: "h2", text: "4.8 Guide, PWA et éléments annexes" },
      { type: "p", text: "L'écran Guide rassemble une pédagogie complète en huit chapitres : créer un compte, choisir une mission, générer l'image avec une IA externe, l'importer, comprendre la validation, gérer son argent, utiliser le parrainage et sécuriser son compte (le guide rappelle notamment que la plateforme ne demande jamais le mot de passe). L'application est une PWA complète : manifeste, icônes, service worker et invite d'installation sur l'écran d'accueil. Un bandeau de rappel de rafraîchissement et un bandeau de retraits récents complètent l'expérience. Les anciens modules de plateforme vidéo, retirés de l'interface lors des travaux précédents, laissent des routes d'API résiduelles à nettoyer (annexe)." },

      { type: "h2", text: "4.9 Panel administrateur" },
      { type: "p", text: "Le panneau d'administration n'est visible que des comptes de rôle admin et s'ouvre depuis le profil. Il couvre : la gestion des utilisateurs (consultation, ajustement manuel des soldes, transfert de fonds, suppression), la validation des dépôts YAS et TRX, le traitement des demandes de retrait, la création et la modification des campagnes de mission (brief, récompense, limites), la réponse aux conversations de support, l'envoi de notifications individuelles ou de diffusions collectives, les statistiques d'activité (analytics) et la configuration globale du programme : taux de conversion FCFA/dollar, récompense par image, seuils des prêts, montant de la caution et conditions de parrainage. Ce panneau est le point de contrôle de toutes les règles décrites dans ce chapitre ; il est aussi, en l'état, protégé par les faiblesses d'authentification décrites au chapitre suivant, ce qui en fait la cible la plus sensible du système." },
    ],
  },
];
