// Contenu Partie 1 — Résumé exécutif, objet, présentation, parcours d'entrée
// Dossier Jeune Élan. Blocs: p (paragraphe), h2/h3 (sous-titres), bullets, table, img.

module.exports = [
  {
    title: "Résumé exécutif",
    blocks: [
      { type: "p", text: "Ce dossier décrit le fonctionnement complet de la plateforme « Jeune Élan » (dépôt GitHub to-be-riche), du parcours d'entrée à la connexion jusqu'aux moindres modules : missions rémunérées d'images, portefeuille multi-comptes, dépôts et retraits, caution, micro-prêts, parrainage, investissements, jeu, trading, chat, notifications et panel administrateur. Il a été établi exclusivement à partir de la lecture du code source (environ 80 routes d'API et une vingtaine d'écrans), sans extrapolation : chaque mécanisme décrit correspond à un fichier vérifiable du projet." },
      { type: "p", text: "Deux analyses complètent la description. La première porte sur la sécurité : le système présente des mécanismes réels et bien pensés (jetons de session rotatifs, vérification par code à usage unique, validation des images par intelligence artificielle), mais souffre de deux failles critiques — un compte administrateur codé en dur dans le code source du dépôt public et des mots de passe stockés en clair — ainsi que de plusieurs vulnérabilités importantes (absence de limitation de débit sur les endpoints sensibles, cookie de session exposé aux scripts, base SQLite sans sauvegarde identifiée)." },
      { type: "p", text: "La seconde analyse répond à la question centrale posée par l'administrateur : le projet va-t-il couler ou être rentable sur le long terme ? La réponse factuelle est sans ambiguïté : en l'état, le modèle économique est structurellement déficitaire. Chaque image validée crée 25 FCFA de dette envers un jeune, chaque gain de roue, chaque bonus de parrainage et chaque rendement d'investissement de 5 % par jour créent du passif, sans qu'aucune source de revenu réelle (sponsor payant, commission, frais, publicité vendue) n'existe dans le code. À 500 jeunes actifs, la seule activité missions génère environ 31,9 millions de FCFA de passif par an. Le projet ne peut devenir rentable qu'en activant des revenus externes (partenariats de marques, frais de service, commissions) et en supprimant les paramètres explosifs, en particulier le rendement quotidien de 5 %. Les chapitres 5 et 6 détaillent les correctifs et les scénarios chiffrés." },
    ],
  },
  {
    title: "1. Objet, périmètre et méthode du dossier",
    blocks: [
      { type: "h2", text: "1.1 Pourquoi ce dossier" },
      { type: "p", text: "L'administrateur de la plateforme a exprimé trois besoins : disposer d'un document expliquant comment tous les aspects du site fonctionnent, pouvoir analyser le système pour identifier d'éventuelles failles, et évaluer si le projet risque de couler ou s'il peut être rentable sur le long terme. Ce dossier répond aux trois questions dans un document unique, pensé pour être lu progressivement : les chapitres 2 à 4 décrivent le système, le chapitre 5 traite la sécurité, le chapitre 6 traite la viabilité financière et le chapitre 7 consolide les recommandations en un plan d'action priorisé." },
      { type: "h2", text: "1.2 Périmètre couvert et limites" },
      { type: "p", text: "Le périmètre couvre l'intégralité du code applicatif du dépôt : écrans (components/screens), routes d'API (app/api), bibliothèques métier (lib), schéma de base de données (prisma/schema.prisma), services annexes (mini-services) et éléments d'installation progressive (manifest, service worker). Le tableau de bord de l'utilisateur a été reconstruit récemment selon la spécification « Étape 1 » avec des données fictives destinées à être remplacées par les vraies données des API existantes ; cette transition est décrite au chapitre 4. En revanche, ce dossier ne couvre pas l'infrastructure d'hébergement effective (non présente dans le dépôt), les contrats commerciaux éventuels conclus hors code avec des marques, ni les obligations fiscales et comptables locales, qui relèvent d'un conseiller juridique et fiscal." },
      { type: "h2", text: "1.3 Méthode" },
      { type: "p", text: "La méthode est celle d'une revue de code statique guidée par les flux d'argent et les flux de données. Chaque affirmation du présent dossier a été vérifiée directement dans les fichiers concernés : lecture du schéma Prisma pour les soldes et conditions, lecture des routes d'authentification pour le cycle d'entrée, lecture des routes de missions, de prêts, de retraits, de jeu et d'investissement pour les règles métier, et tests fonctionnels dans un navigateur pour confirmer le comportement de l'interface. Les montants chiffrés du chapitre 6 sont des projections illustratives fondées sur les paramètres réels du code (25 FCFA par image, limite de 10 images par jour, taux de change interne), clairement signalées comme hypothèses." },
    ],
  },
  {
    title: "2. Présentation générale de la plateforme",
    blocks: [
      { type: "h2", text: "2.1 Identité et concept" },
      { type: "p", text: "« Jeune Élan » est une application financière et éducative destinée à un public de jeunes en Afrique de l'Ouest, précédemment nommée « Be Rich » / « To Be Rich » puis « Espace Jeunes ». Le concept affiché est résumé par la promesse d'accueil : « Créez. Gagnez. Empruntez. » Le jeune crée des visuels publicitaires à l'aide d'outils d'intelligence artificielle externes (ChatGPT, DALL-E, Midjourney ou tout autre générateur de son choix), les importe sur la plateforme, et chaque image validée par le système lui rapporte 25 FCFA. En accumulant des gains, une caution et des parrainages, il débloque l'accès à des micro-prêts de 5 000 ou 10 000 FCFA. Autour de ce noyau gravitent des modules complémentaires : parrainage, niveaux d'investissement, roue de la fortune, trading simulé avec arène de classement, chat avec assistant IA et support humain, guide pédagogique complet et panneau d'administration." },
      { type: "p", text: "Le public visé est mobile : l'application est construite comme une application de type téléphone (cadre vertical de 430 pixels maximum), avec une barre de navigation basse à six entrées (Tableau, Accueil, Finance, Portefeuille, Guide, Profil), installable comme application progressive (PWA) sur l'écran d'accueil du smartphone. La langue de l'interface est intégralement le français." },
      { type: "h2", text: "2.2 Stack technique et architecture" },
      { type: "p", text: "La plateforme est une application monopage Next.js 16 (App Router) écrite en React 19 et TypeScript, stylée avec Tailwind CSS 4 et la bibliothèque de composants shadcn/ui. Les données sont persistées dans une base SQLite via Prisma ORM ; l'état côté client est géré par Zustand ; le temps réel du chat s'appuie sur Socket.io via un mini-service séparé ; les courriels de vérification passent par Resend, Gmail ou un mode simulation selon la configuration. L'application expose environ 80 routes d'API réparties par domaine (auth, missions, prêts, dépôts, retraits, invest, jeu, trading, chat, admin, notifications, parrainage) et une vingtaine d'écrans chargés dynamiquement pour des performances optimales." },
      { type: "table", caption: "Tableau 1 : composants techniques principaux et leur rôle", headers: ["Composant", "Rôle dans le système"], widths: [30, 70], rows: [
        ["Next.js 16 + React 19", "Cadre applicatif, rendu des écrans, routes d'API (app/api)"],
        ["TypeScript", "Typage statique de tout le code applicatif"],
        ["Tailwind CSS 4 + shadcn/ui", "Interface visuelle et composants réutilisables"],
        ["Prisma ORM + SQLite", "Persistance des utilisateurs, soldes, images, prêts, transactions"],
        ["Zustand", "État global côté client (session, page courante, notifications)"],
        ["Socket.io (mini-service)", "Temps réel du chat entre jeunes, bot et administrateur"],
        ["Resend / Gmail / simulation", "Envoi des codes de vérification par courriel"],
        ["PWA (manifest + service worker)", "Installation sur mobile, mode hors-ligne partiel"],
      ]},
      { type: "h2", text: "2.3 Données et monnaies internes" },
      { type: "p", text: "Le schéma de données distingue plusieurs soldes par utilisateur : solde principal, solde missions, solde jeu, solde d'investissement, solde de projet et solde de trading. Les récompenses de missions sont libellées en FCFA mais enregistrées en dollars américains dans la base, à partir d'un taux de conversion configurable par l'administrateur (cfaUsdRate) ; l'interface reconvertit à l'affichage. Cette double devise est un point de vigilance comptable détaillé au chapitre 5. Les autres objets persistés incluent les campagnes de mission, les images soumises avec leur statut de validation, la caution, les prêts et leurs remboursements, les dépôts en attente (YAS, TRX, mobile money), les retraits, les filleuls, les niveaux d'investissement, les notifications et l'historique complet des transactions." },
    ],
  },
  {
    title: "3. Parcours d'entrée : inscription, OTP et connexion",
    blocks: [
      { type: "h2", text: "3.1 Création de compte" },
      { type: "p", text: "L'entrée dans la plateforme se fait par l'écran d'authentification, qui offre deux modes : connexion et inscription. L'inscription exige un nom complet, une adresse électronique, un mot de passe d'au moins six caractères confirmé deux fois et un numéro de téléphone ; un code de parrainage peut être saisi facultativement, ce qui lie le nouveau compte à son parrain. Le serveur vérifie l'unicité de l'adresse et du téléphone, génère un code de parrainage propre au nouveau compte, puis crée l'enregistrement utilisateur avec un jeton de session provisoire. À ce stade, le compte n'est pas encore actif : il reste marqué non vérifié jusqu'à la confirmation du courriel." },
      { type: "h2", text: "3.2 Vérification par code à usage unique (OTP)" },
      { type: "p", text: "La plateforme envoie immédiatement un code à six chiffres à l'adresse indiquée. Ce code est valable dix minutes, et il est stocké en base sous forme hachée (SHA-256), jamais en clair. Trois canaux d'envoi sont prévus selon la configuration : le fournisseur Resend, un compte Gmail, ou un mode simulation qui affiche le code directement à l'écran — c'est ce mode qui est actif lorsque aucune clé d'API n'est configurée, ce qui est le cas de l'environnement de développement actuel. Dès que le jeune saisit le bon code, le compte est marqué vérifié et surtout le jeton de session est régénéré : toute session ouverte avant la vérification devient invalide. Ce mécanisme de rotation est une protection anti-fraude bien conçue, volontairement discrète dans l'interface." },
      { type: "h2", text: "3.3 Connexion et gestion des sessions" },
      { type: "p", text: "La connexion compare le mot de passe soumis à celui enregistré (voir le chapitre 5 pour le problème de stockage en clair), puis délivre un jeton de session de 32 caractères hexadécimaux aléatoires, déposé dans un cookie nommé br_token valable sept jours. Chaque nouvelle connexion régénère ce jeton : un compte ne peut donc pas rester connecté simultanément sur deux appareils, l'ancien appareil est silencieusement déconnecté. Les routes d'API authentifient chaque requête par ce jeton, via l'en-tête X-Auth-Token ou le cookie, et les réponses serveur ne renvoient jamais le mot de passe ni le jeton dans les données utilisateur. Le même parcours existe pour la récupération de mot de passe : un code est envoyé par courriel, une page de réinitialisation protégée permet d'en définir un nouveau." },
      { type: "p", text: "Après connexion, l'utilisateur arrive directement sur l'écran « Tableau », point d'entrée du tableau de bord décrit au chapitre suivant. Une page d'accueil promotionnelle (splash) affiche le logo et la promesse du service pendant le chargement, et l'application propose son installation sur l'écran d'accueil du téléphone via le manifeste PWA." },
    ],
  },
];
