// Contenu Partie 3 — Sécurité, viabilité financière, conclusions, annexe
const ASSETS = "/home/z/my-project/scripts/assets";

module.exports = [
  {
    title: "5. Analyse de sécurité : failles identifiées et correctifs",
    blocks: [
      { type: "p", text: "L'objectif de ce chapitre est de permettre à l'administrateur d'analyser le système sans laisser de faille exploitable. L'analyse distingue d'abord ce qui est déjà solide, puis recense les vulnérabilités par ordre de gravité, chacune rattachée à son fichier et à son correctif concret. Aucune faille listée ici n'est théorique : toutes ont été constatées dans le code du dépôt." },

      { type: "h2", text: "5.1 Mécanismes de sécurité existants et efficaces" },
      { type: "p", text: "Plusieurs dispositifs sont correctement implémentés et méritent d'être conservés. Les jetons de session sont des valeurs aléatoires de 32 caractères hexadécimaux, régénérées à chaque connexion et à chaque vérification de courriel : ce mécanisme de rotation invalide automatiquement les sessions volées ou obsolètes et empêche la connexion simultanée d'un même compte sur plusieurs appareils. Les codes de vérification sont valables dix minutes et stockés hachés en SHA-256, jamais en clair. Les réponses d'API excluent systématiquement le mot de passe et le jeton des données renvoyées au client. Les montants critiques (niveaux d'investissement, plafonds de mission, conditions de prêt, coût et gains de la roue) sont calculés et contrôlés côté serveur, et le tirage de la roue est déterminé côté serveur. Enfin, l'affichage dynamique du texte utilise une fonction d'échappement protectrice contre l'injection de scripts (XSS) dans les zones sensibles." },

      { type: "h2", text: "5.2 Failles identifiées, impact et correctifs" },
      { type: "p", text: "Le tableau ci-dessous hiérarchise les failles constatées. Deux d'entre elles sont critiques : elles exposent l'intégralité du système à quiconque lit le code source public du dépôt GitHub, et doivent être corrigées avant toute mise en production ou toute communication autour du projet." },
      { type: "table", caption: "Tableau 2 : registre des vulnérabilités constatées dans le code", headers: ["Gravité", "Faille constatée", "Impact concret", "Correctif recommandé"], widths: [12, 30, 28, 30], rows: [
        ["Critique", "Compte administrateur codé en dur dans la route de connexion : adresse et mot de passe en clair dans le code source, sur un dépôt GitHub public", "Toute personne lisant le dépôt obtient le contrôle total : soldes, retraits, suppression d'utilisateurs", "Supprimer le compte en dur ; créer l'admin en base avec rôle et mot de passe haché ; réécrire l'historique du secret ; changer le mot de passe"],
        ["Critique", "Mots de passe des utilisateurs stockés en clair dans la base de données", "Toute fuite de la base compromet tous les comptes, avec réutilisation probable des mots de passe sur d'autres services", "Hacher avec bcrypt ou argon2 à l'inscription ; migration progressive à la prochaine connexion ; jamais de mot de passe en clair ni dans les logs"],
        ["Élevée", "Aucune limitation de débit sur les routes d'authentification et d'OTP", "Bombardement de courriels, force brute des mots de passe et des codes, coût d'API", "Limitation par IP et par compte (ex. 5 tentatives / 10 minutes), temporisation croissante, journalisation des échecs"],
        ["Élevée", "Cookie de session sans indicateur httpOnly ni secure", "Un script injecté (XSS résiduel) ou une interception HTTP permet de voler la session", "Activer httpOnly, secure en production, conserver sameSite lax ; envisager la liaison au périphérique"],
        ["Élevée", "Téléphone demandé à l'inscription mais jamais vérifié ; aucun contrôle anti-multi-comptes", "Auto-parrainage massif par création de comptes, fraude aux bonus de 20 % et aux seuils", "Vérification par SMS (OTP téléphone), détection d'adresses IP et d'empreintes partagées, plafonnement des bonus par appareil"],
        ["Moyenne", "Images soumises stockées en base 64 dans SQLite", "Gonflement rapide de la base (une image = plusieurs centaines de Ko), sauvegardes lourdes, ralentissements", "Stockage objet (fichiers ou S3) avec identifiant en base ; compression à l'import ; purge déjà prévue à conserver"],
        ["Moyenne", "Validation d'image heuristique : empreinte limitée aux premiers caractères, détection d'images d'internet non garantie", "Soumissions recyclées ou copiées rémunérées à tort, dilution du passif de missions", "Empreinte perceptuelle (pHash) sur l'image décodée, comparaison par lot, vérification de provenance par IA renforcée"],
        ["Moyenne", "Base SQLite unique en production, sans sauvegarde automatisée identifiée", "Perte de données irréversible, interruption de service, litiges de soldes non prouvables", "Sauvegardes quotidiennes chiffrées hors site ; bascule PostgreSQL (compatible Prisma) avant montée en charge"],
        ["Moyenne", "Double devise FCFA/dollar gérée par un taux configurable, sans journal de conversion", "Écarts d'arrondi, soldes contestables, comptabilité invérifiable", "Journaliser chaque conversion (date, taux, montants), arrondi réglementé, taux figé par jour"],
        ["Faible", "Code mort (routes vidéo résiduelles), fichiers temporaires volumineux dans le répertoire de travail (captures, journaux d'outils, téléversements)", "Surface d'attaque et confusion inutiles, dépôt alourdi", "Supprimer les routes mortes, ajouter les exclusions au contrôle de version, nettoyer le répertoire"],
        ["Faible", "Jeton d'accès GitHub personnel manipulé en clair pendant les travaux", "Compromission du dépôt si le jeton a fuité", "Révoquer le jeton immédiatement et en créer un neuf à usage restreint"],
      ]},

      { type: "h2", text: "5.3 Plan de correction priorisé" },
      { type: "p", text: "La correction recommandée suit l'ordre de gravité. Avant toute ouverture au public : suppression du compte administrateur en dur (avec réécriture du secret dans l'historique du dépôt et changement du mot de passe), hachage bcrypt des mots de passe avec migration transparente à la prochaine connexion, et activation de httpOnly/secure sur le cookie de session. Dans la foulée : limitation de débit sur toutes les routes d'authentification, vérification SMS du téléphone et contrôles anti-multi-comptes orientés parrainage. Dans un second temps : migration des images vers un stockage objet, sauvegarde quotidienne chiffrée, journal des conversions de devise, puis nettoyage du code mort. Chaque correctif est localisé (un à trois fichiers), compatible avec l'architecture actuelle et réalisable sans refonte." },
    ],
  },
  {
    title: "6. Analyse de viabilité financière pour l'administrateur",
    blocks: [
      { type: "p", text: "La question posée est directe : l'administrateur va-t-il couler, ou le projet sera-t-il rentable sur le long terme ? La réponse exige d'abord de recenser où l'argent entre réellement, où il sort, puis de chiffrer le déséquilibre, avant d'examiner sous quelles conditions le modèle peut devenir viable." },

      { type: "h2", text: "6.1 Où l'argent entre — et où il ne rentre pas" },
      { type: "p", text: "Trois flux font entrer de l'argent réel sur la plateforme : les dépôts des jeunes (YAS, TRX, mobile money), les cautions de 5 000 FCFA et les placements d'investissement (5 à 3 000 $). Ces flux sont des dettes envers les utilisateurs, pas des revenus : chaque franc déposé reste exigible. En face, les dépenses réelles de l'administrateur sont les retraits validés, les frais de transaction mobile money et blockchain, les coûts d'hébergement et de domaine, les appels d'API de validation d'images et de messagerie, et le temps de modération humaine. Le point décisif est le suivant : le code ne contient aucune source de revenu. Aucune commission sur retrait, aucun frais de dossier sur prêt (remboursés à montant nominal), aucun sponsor payant rattaché aux campagnes de mission, aucune publicité vendue — les bandeaux publicitaires affichés lors des changements d'onglet ont été supprimés et étaient de toute façon fictifs, sans régie ni contrat. Le seul « produit » de la plateforme, le visuel publicitaire créé par le jeune, n'est monétisé nulle part : il est payé sans être vendu." },

      { type: "h2", text: "6.2 Le problème structurel : un passif qui croît sans revenu" },
      { type: "p", text: "Chaque activité de la plateforme crée de la dette envers les utilisateurs : 25 FCFA par image validée, les gains de la roue (jusqu'à 10 $ par tirage), le bonus de 20 % par filleul validé, et surtout le rendement de 5 % par jour des investissements — un placement de niveau 3 à 3 000 $ émet théoriquement 150 $ chaque jour, soit plus de 1 000 $ par semaine, sans qu'aucun actif réel ne produise ces montants. Comme aucune entrée de revenu ne compense ces émissions, la position de trésorerie de l'administrateur ne peut mathématiquement que se dégrader avec chaque utilisateur actif. Les verrous actuels (délai de 24 heures après le premier dépôt, parrainages requis croissants à chaque retrait, validation manuelle des retraits) ne suppriment pas cette dette : ils la rendent simplement plus lente à se matérialiser, tout en l'aggravant au passage puisque les parrainages exigés pour retirer génèrent eux-mêmes du passif de missions. Un tel montage, où les dépôts des nouveaux arrivants servent à honorer les retraits des anciens, est de plus structurellement assimilable à un schéma de type pyramide : il fonctionne tant que la croissance des entrées dépasse les sorties, puis s'effondre au premier ralentissement." },
      { type: "img", path: ASSETS + "/fig1_passif_missions.png", caption: "Figure 1 : passif hebdomadaire généré par les seules missions (25 F par image, 7 images validées par jour et par jeune), selon le nombre de jeunes actifs", width: 620 },
      { type: "p", text: "À titre d'ordre de grandeur, 500 jeunes actifs au rythme moyen de sept images validées par jour représentent à eux seuls 61 875 FCFA de récompenses par jour, soit environ 1,9 million par mois et 31,9 millions par an. Ce passif précède même les frais fixes : chaque appel de validation d'images, chaque courriel et chaque heure de modération s'ajoutent par-dessus. La figure 1 montre la progression de cette charge avec la taille de la communauté — la croissance, loin de résoudre le problème, l'amplifie linéairement." },

      { type: "h2", text: "6.3 Scénarios d'évolution chiffrés" },
      { type: "p", text: "Les scénarios ci-dessous illustrent, à communauté constante de 500 jeunes actifs, l'effet de trois stratégies sur le résultat brut annuel de l'administrateur (récompenses de missions uniquement, avant frais fixes et avant les émissions de jeu, parrainage et investissement). Ils reposent sur les paramètres réels du code et des hypothèses de sponsor explicitées ; ce sont des projections illustratives, non des données observées." },
      { type: "table", caption: "Tableau 3 : scénarios annuels comparés à 500 jeunes actifs (illustratif)", headers: ["Scénario", "Hypothèses", "Revenus annuels", "Passif missions", "Résultat brut"], widths: [22, 34, 15, 15, 14], rows: [
        ["A. Statu quo", "Aucun revenu activé, fonctionnement actuel du code", "0 FCFA", "31,9 M FCFA", "-31,9 M FCFA"],
        ["B. Sponsors de marques", "30 % des images sponsorisées à 75 FCFA payés par la marque (soit 383 000 visuels achetés dans l'année)", "28,7 M FCFA", "31,9 M FCFA", "-3,2 M FCFA"],
        ["C. Modèle diversifié", "Sponsors 30 % à 75 FCFA, frais de service de 3 % sur retraits et frais de dossier de 5 % sur prêts (volumes estimés)", "36,0 M FCFA", "31,9 M FCFA", "+4,1 M FCFA"],
      ]},
      { type: "img", path: ASSETS + "/fig2_scenarios.png", caption: "Figure 2 : comparaison des trois scénarios annuels (millions de FCFA) — le résultat net du scénario C reste fragile face aux émissions de jeu, de parrainage et d'investissement non incluses", width: 660 },
      { type: "p", text: "La lecture des scénarios est claire. Le statu quo (A) cumule un déficit de plus de 31 millions de FCFA par an avant même les frais d'exploitation, et coule dès que les retraits s'accumulent au rythme des gains. Le scénario B, où des marques paieraient réellement trois visuels sur dix à 75 FCFA, reste légèrement déficitaire sur le seul périmètre missions : il montre que le sponsoring seul, à un taux de couverture réaliste, ne suffit pas. Seul le scénario C — sponsoring combiné à des frais de service (retraits, dossiers de prêt) — franchit le seuil de rentabilité brut, avec une marge volontairement mince : rappelons que les émissions de la roue, des bonus de parrainage et des rendements d'investissement de 5 % par jour, non incluses dans ce calcul, effaceraient cette marge si elles n'étaient pas supprimées ou plafonnées. La conclusion opérationnelle est double : il faut activer des revenus réels, et simultanément éteindre les émissions non couvertes, en premier lieu le rendement quotidien de 5 %." },

      { type: "h2", text: "6.4 Risques réglementaires et réputationnels" },
      { type: "p", text: "Trois risques non financiers pèsent lourd sur la viabilité. Réglementaire d'abord : collecter des dépôts et des cautions, accorder du crédit et convertir des monnaies sont, dans l'ensemble de la zone UEMOA régie par la BCEAO, des activités réservées aux établissements agréés (microfinance, monnaie électronique, services de paiement) ; exploiter ces services sans agrément expose l'administrateur à des sanctions et à la responsabilité personnelle des fonds collectés. Ce dossier ne remplace pas un avis juridique, mais le sujet doit être traité avant toute mise en production grand public, par exemple via un partenariat avec un établissement agréé ou un repositionnement du produit hors du crédit et de la collecte. Réputationnel ensuite : promettre des gains réels que la trésorerie ne peut honorer transforme rapidement les délais de retrait en litiges publics, avec un effet catastrophique sur le recrutement de nouveaux jeunes dont dépend précisément la trésorerie. Opérationnel enfin : la fraude multi-comptes (auto-parrainage) et les soumissions d'images copiées diluent les budgets de récompense sans produire de valeur monétisable pour un futur sponsor." },

      { type: "h2", text: "6.5 Verdict : couler ou être rentable ?" },
      { type: "p", text: "En l'état actuel du code, sans revenu activé et avec des émissions non couvertes, le projet coulera : la trésorerie ne peut que baisser, les verrous de retrait ne font que retarder l'échéance tout en l'aggravant, et le risque réglementaire s'ajoute au risque financier. Le projet n'est toutefois pas condamné par sa technologie, qui fonctionne, ni par son concept d'engagement, qui produit un actif réel — une communauté de jeunes capables de produire des visuels publicitaires. Il est condamné uniquement par l'absence de monétisation de cet actif. La rentabilité à long terme est atteignable à trois conditions cumulatives, détaillées au chapitre suivant : activer des revenus réels (sponsors de marques payant à l'image, frais de service raisonnables et assumés), plafonner ou supprimer les émissions non couvertes (rendement de 5 % par jour, gains de roue retirables, bonus de parrainage monétaires), et régler le statut réglementaire des activités de dépôt et de crédit. Sans ces trois conditions, le scénario A s'impose ; avec elles, le scénario C devient crédible et scalable." },
    ],
  },
  {
    title: "7. Conclusions et plan d'action recommandé",
    blocks: [
      { type: "p", text: "Le système « Jeune Élan » est techniquement fonctionnel et complet : le parcours d'entrée par OTP est robuste, le cœur métier missions-éligibilité-prêts est cohérent, l'interface est soignée et le panneau d'administration couvre l'ensemble des paramètres du programme. Les faiblesses identifiées ne relèvent pas de l'architecture mais de deux décisions de sécurité (mot de passe en clair, compte administrateur en dur) et d'un modèle économique inachevé (un passif émis sans revenu en face). Le plan d'action ci-dessous consolide l'ensemble des recommandations de ce dossier en trois horizons." },
      { type: "table", caption: "Tableau 4 : plan d'action consolidé et priorisé", headers: ["Horizon", "Actions prioritaires", "Résultat attendu"], widths: [16, 52, 32], rows: [
        ["Immédiat (avant toute ouverture publique)", "Supprimer l'administrateur codé en dur et changer le secret ; hacher les mots de passe (bcrypt) ; activer httpOnly/secure sur le cookie ; limiter le débit des routes d'authentification ; révoquer le jeton GitHub exposé", "Surface d'attaque critique fermée ; base et dépôt non compromis"],
        ["Court terme (1 à 3 mois)", "Remplacer les données fictives du tableau de bord par les API ; vérification SMS et contrôles anti-multi-comptes ; sauvegardes quotidiennes chiffrées ; suppression du rendement de 5 %/jour et plafonnement des gains retirables ; journal des conversions de devise", "Fraude contenue ; passif maîtrisé ; données recouvrables"],
        ["Moyen terme (3 à 6 mois)", "Signer des sponsors de marques réels payant à l'image (objectif : couvrir au moins 30 % des visuels) ; introduire des frais de service transparents sur retraits et dossiers de prêt ; statuer sur la conformité réglementaire (partenariat agréé ou recentrage du produit) ; basculer vers PostgreSQL et un stockage objet des images", "Revenus réels actifs ; modèle proche du scénario C ; trajectoire de rentabilité crédible"],
      ]},
      { type: "p", text: "La recommandation finale tient en une phrase : ne pas ouvrir la plateforme au public dans son état actuel, corriger d'abord les deux failles critiques, puis faire du chapitre 6 une règle de gouvernance — aucune émission de gains sans revenu correspondant en face. Tant que cette équation n'est pas respectée, chaque nouveau jeune actif rapproche l'administrateur de l'insolvabilité ; dès qu'elle l'est, la communauté devient au contraire l'actif le plus précieux du projet." },
    ],
  },
  {
    title: "Annexe : cartographie des modules et principales routes d'API",
    blocks: [
      { type: "p", text: "Cette annexe sert de référence rapide pour l'audit et la maintenance : chaque module fonctionnel est rattaché à ses routes d'API réelles dans le dépôt, ce qui permet de localiser immédiatement le code correspondant à toute règle décrite dans ce dossier. Les routes obsolètes (plateforme vidéo retirée de l'interface) sont signalées pour nettoyage." },
      { type: "table", caption: "Tableau 5 : modules et routes d'API correspondantes", headers: ["Module", "Routes principales", "Observations"], widths: [22, 46, 32], rows: [
        ["Authentification", "/api/auth/register, /api/auth/otp, /api/auth/login, /api/auth/session, /api/auth/logout, /api/auth/forgot-password, /api/auth/reset-password", "OTP haché ; rotation du jeton de session ; failles critiques à corriger (chapitre 5)"],
        ["Missions", "/api/missions/dashboard, /campaigns, /images, /validate, /eligibility, /caution", "Validation IA asynchrone ; 25 FCFA par image ; limite 10/jour ; purge quotidienne"],
        ["Prêts", "/api/missions/loans, /api/missions/loans/[id]", "5 000 et 10 000 FCFA ; échéance 30 jours ; approbation administrative ; sans intérêt"],
        ["Portefeuille et transactions", "/api/transfer, /api/notifications", "Comptes séparés principal/missions/jeu/investissement/projet"],
        ["Dépôts", "/api/deposit, /api/deposit/yas, /api/deposit/trx, /api/deposit/check", "En attente jusqu'à validation admin ; un seul dépôt en attente à la fois"],
        ["Retraits", "/api/withdrawal, /api/withdrawal/yas, /api/withdrawal/convert-trx-tmoney", "Délai de 24 h après premier dépôt ; parrainages requis croissants ; validation admin"],
        ["Parrainage", "/api/referral/list", "Code unique ; bonus de 20 % ; seuils 5 / 12 / 25 selon les usages"],
        ["Investissements", "/api/invest/list, /create, /claim, /unlock", "3 niveaux en dollars ; rendement 5 %/jour à supprimer (chapitre 6)"],
        ["Jeu", "/api/game/spin, /api/game/status", "Roue 12 segments ; tirage serveur ; 10 tours/jour"],
        ["Trading et arène", "/api/trading/prices, /positions, /open-position, /close-position, /history, /leaderboard, /chart ; /api/trade/*", "Simulation de marché ; classement compétitif"],
        ["Chat et support", "/api/chat/bot, /send, /messages, /ticket, /escalate, /tip", "Assistant IA puis escalade humaine ; temps réel Socket.io"],
        ["Administration", "/api/admin/data, /users/[id], /update-balance, /transfer-funds, /delete-user, /campaigns, /withdrawals, /deposits, /yas-deposits, /notifications, /send-notification, /broadcasts, /chats, /chat-reply, /support, /config, /analytics", "Contrôle total du programme ; cible la plus sensible (chapitre 5)"],
        ["Notifications", "/api/notifications, /api/notifications/daily", "Compteur non-lues ; notification du jour ; diffusion collective"],
        ["Obsolète", "/api/videos/*, /api/projects/*, /api/enterprise/*, /api/gains/*", "Plateforme vidéo retirée de l'interface ; routes résiduelles à supprimer"],
      ]},
      { type: "p", text: "Pour toute évolution future du tableau de bord (Étape 2 et suivantes de la spécification), les données fictives actuellement en place sont calquées sur les réponses des routes missions/dashboard, missions/campaigns et referral/list : le remplacement se fait donc point par point, sans modification de l'interface ni des autres modules." },
    ],
  },
];
